/** Generated by scripts/generate-explorer-icon-manifest.mjs - do not edit manually */
export const EXPLORER_ICON_MANIFEST: Record<string, readonly string[]> = {
  "blockscout": ["svg"],
  "etherscan": ["svg"],
  "oklink": ["svg"],
  "routescan": ["svg"]
};
