/** Generated by scripts/generate-pt-icon-fallback.mjs - do not edit manually */
/** Upstream PT token icon fallback mappings extracted from reservePatches.ts */
export const PT_ICON_FALLBACK_MAP: Record<string, string> = {
  "eusde": "pteusde",
  "srusde": "srusde",
  "susde": "ptsusde",
  "usde": "ptusde"
};
